// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdmfhkkgcdnisikrlsak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkbWZoa2tnY2RuaXNpa3Jsc2FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTU0MzksImV4cCI6MjA2NTQ5MTQzOX0.Yc8NNyjTgpMT9Kpcn9ttorlkNoW2-fsWv4D0h-0kXE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);